-- AppOverall — migrazione dati: l'Allegato IV, copia per la sola migrazione.
--
-- GENERATO da genera_allegato_iv.js, non si modifica a mano.
-- Fonte: formazione-81-utils-src, allegato_iv_asr2025.js, commit 736699e.
-- 88 divisioni ATECO 2007 agg. 2022. `dedotto` = il valore non si legge nel
-- testo vigente e viene dal 2011 (decisione 5): si porta, perche' chi confronta deve
-- poter dire quanta deduzione c'e' nel default.
--
-- A grana di divisione ATECO 2007 e ATECO 2022 sono lo stesso insieme di 88 codici
-- (AppFormazione, migrazione 0048), e l'allegato dice di se' «ancorata ad ATECO 2007
-- agg. 2022»: il valore '2007' di `sede.ateco_versione` e' questo.

create table if not exists origine.allegato_iv (
  divisione text primary key,
  sezione text not null,
  livello text not null check (livello in ('basso', 'medio', 'alto')),
  dedotto boolean not null,
  fonte text
);

insert into origine.allegato_iv (divisione, sezione, livello, dedotto, fonte) values
  ('01', 'A', 'medio', false, null),
  ('02', 'A', 'medio', false, null),
  ('03', 'A', 'medio', false, null),
  ('05', 'B', 'alto', false, null),
  ('06', 'B', 'alto', false, null),
  ('07', 'B', 'alto', false, null),
  ('08', 'B', 'alto', false, null),
  ('09', 'B', 'alto', false, null),
  ('10', 'C', 'alto', false, null),
  ('11', 'C', 'alto', false, null),
  ('12', 'C', 'alto', false, null),
  ('13', 'C', 'alto', false, null),
  ('14', 'C', 'alto', false, null),
  ('15', 'C', 'alto', false, null),
  ('16', 'C', 'alto', false, null),
  ('17', 'C', 'alto', false, null),
  ('18', 'C', 'alto', false, null),
  ('19', 'C', 'alto', false, null),
  ('20', 'C', 'alto', false, null),
  ('21', 'C', 'alto', false, null),
  ('22', 'C', 'alto', false, null),
  ('23', 'C', 'alto', false, null),
  ('24', 'C', 'alto', false, null),
  ('25', 'C', 'alto', false, null),
  ('26', 'C', 'alto', false, null),
  ('27', 'C', 'alto', false, null),
  ('28', 'C', 'alto', false, null),
  ('29', 'C', 'alto', false, null),
  ('30', 'C', 'alto', true, 'Allegato II Accordo 221/CSR del 21/12/2011, GU n.8 dell''11/01/2012 p. 48, atto 12A00059 — il testo vigente tace per guasto tipografico, non per scelta'),
  ('31', 'C', 'alto', false, null),
  ('32', 'C', 'alto', false, null),
  ('33', 'C', 'alto', false, null),
  ('35', 'D', 'alto', false, null),
  ('36', 'E', 'alto', false, null),
  ('37', 'E', 'alto', false, null),
  ('38', 'E', 'alto', false, null),
  ('39', 'E', 'alto', false, null),
  ('41', 'F', 'alto', false, null),
  ('42', 'F', 'alto', false, null),
  ('43', 'F', 'alto', false, null),
  ('45', 'G', 'basso', false, null),
  ('46', 'G', 'basso', false, null),
  ('47', 'G', 'basso', false, null),
  ('49', 'H', 'medio', false, null),
  ('50', 'H', 'medio', false, null),
  ('51', 'H', 'medio', false, null),
  ('52', 'H', 'medio', false, null),
  ('53', 'H', 'medio', false, null),
  ('55', 'I', 'basso', false, null),
  ('56', 'I', 'basso', false, null),
  ('58', 'J', 'basso', false, null),
  ('59', 'J', 'basso', false, null),
  ('60', 'J', 'basso', false, null),
  ('61', 'J', 'basso', false, null),
  ('62', 'J', 'basso', false, null),
  ('63', 'J', 'basso', false, null),
  ('64', 'K', 'basso', false, null),
  ('65', 'K', 'basso', false, null),
  ('66', 'K', 'basso', false, null),
  ('68', 'L', 'basso', false, null),
  ('69', 'M', 'basso', false, null),
  ('70', 'M', 'basso', false, null),
  ('71', 'M', 'basso', false, null),
  ('72', 'M', 'basso', false, null),
  ('73', 'M', 'basso', false, null),
  ('74', 'M', 'basso', false, null),
  ('75', 'M', 'basso', false, null),
  ('77', 'N', 'basso', false, null),
  ('78', 'N', 'basso', false, null),
  ('79', 'N', 'basso', false, null),
  ('80', 'N', 'basso', false, null),
  ('81', 'N', 'basso', false, null),
  ('82', 'N', 'basso', false, null),
  ('84', 'O', 'medio', false, null),
  ('85', 'P', 'medio', false, null),
  ('86', 'Q', 'alto', true, 'Allegato II Accordo 221/CSR del 21/12/2011, GU n.8 dell''11/01/2012 p. 48, atto 12A00059 — il testo vigente tace per guasto tipografico, non per scelta'),
  ('87', 'Q', 'alto', true, 'Allegato II Accordo 221/CSR del 21/12/2011, GU n.8 dell''11/01/2012 p. 48, atto 12A00059 — il testo vigente tace per guasto tipografico, non per scelta'),
  ('88', 'Q', 'medio', false, null),
  ('90', 'R', 'basso', false, null),
  ('91', 'R', 'basso', false, null),
  ('92', 'R', 'basso', false, null),
  ('93', 'R', 'basso', false, null),
  ('94', 'S', 'basso', false, null),
  ('95', 'S', 'basso', false, null),
  ('96', 'S', 'basso', false, null),
  ('97', 'T', 'basso', false, null),
  ('98', 'T', 'basso', false, null),
  ('99', 'U', 'basso', false, null)
on conflict (divisione) do nothing;
