-- AppOverall — seed: il testo d'origine dei 268 alias
--
-- Si carica DOPO la `0008`, che aggiunge le tre colonne. Ogni riga aggiorna un
-- alias esistente: non ne crea e non ne toglie, quindi il conto resta 268 e il
-- carico si rifiuta da se se un testo non trova la sua riga.
--
-- I 268 vengono da `docs/c1a/alias-testi-origine.json` di AppSopralluoghi
-- (`ede5112`), estratti dal catalogo del gestionale datato 30/07/2026 17:04.
-- L'impronta dei testi in ordine di riga e verificata **prima** di generare
-- questo file e **dopo** il carico, con la query in fondo.
--
--   sha256 dei 268 testo_origine, separati da \n, in ordine di riga_foglio:
--   9742ecef39efb97daf27279a6cfb17e0991884729eec053570f224ff50865f30
--
-- **Perche `riga_foglio` e una colonna e non un commento.** Quell'impronta si
-- ricontrolla solo ordinando come e stata calcolata. `corso_alias` ha per chiave
-- `testo`, e ordinare per `testo` segue la **collation** del database: darebbe un
-- terzo hash e farebbe concludere che il carico e rotto. E la trappola A11, un
-- piano piu a valle — vedi il programma all'11 settembre 2026.

begin;

update corso_alias set estrazione = 'catalogo_20260730';

update corso_alias set testo_origine = 'Addetto a lavori in spazi confinati e sospetti di inquinamento', riga_foglio = 3 where testo = 'ADDETTO A LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO';
update corso_alias set testo_origine = 'ADDETTO AI LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO', riga_foglio = 4 where testo = 'ADDETTO AI LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO';
update corso_alias set testo_origine = 'ADDETTO AL MONTAGGIO, SMONTAGGIO, TRASFORMAZIONE DI PONTEGGI O PER PREPOSTI ALLA SORVEGLIANZA', riga_foglio = 5 where testo = 'ADDETTO AL MONTAGGIO, SMONTAGGIO, TRASFORMAZIONE DI PONTEGGI O PER PREPOSTI ALLA SORVEGLIANZA';
update corso_alias set testo_origine = 'Addetto alla conduzione di autoribaltabili a cingoli', riga_foglio = 6 where testo = 'ADDETTO ALLA CONDUZIONE DI AUTORIBALTABILI A CINGOLI';
update corso_alias set testo_origine = 'Addetto alla conduzione di carrelli elevatori semoventi con conducente a bordo (Carrelli industriali semoventi)', riga_foglio = 7 where testo = 'ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI)';
update corso_alias set testo_origine = 'Addetto alla conduzione di carrelli elevatori semoventi con conducente a bordo (Carrelli industriali semoventi, carrelli semoventi a braccio telescopico, carrelli/sollevatori/elevatori semoventi telescopici rotativi)', riga_foglio = 8 where testo = 'ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, CARRELLI SEMOVENTI A BRACCIO TELESCOPICO, CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)';
update corso_alias set testo_origine = 'Addetto alla conduzione di carrelli elevatori semoventi con conducente a bordo (Carrelli semoventi a braccio telescopico)', riga_foglio = 9 where testo = 'ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI SEMOVENTI A BRACCIO TELESCOPICO)';
update corso_alias set testo_origine = 'Addetto alla conduzione di carrelli elevatori semoventi con conducente a bordo (Carrelli/sollevatori/elevatori semoventi telescopici rotativi)', riga_foglio = 10 where testo = 'ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)';
update corso_alias set testo_origine = 'ADDETTO ALLA CONDUZIONE DI CARROPONTE E GRU A BANDIERA', riga_foglio = 11 where testo = 'ADDETTO ALLA CONDUZIONE DI CARROPONTE E GRU A BANDIERA';
update corso_alias set testo_origine = 'Addetto alla conduzione di escavatori a fune', riga_foglio = 12 where testo = 'ADDETTO ALLA CONDUZIONE DI ESCAVATORI A FUNE';
update corso_alias set testo_origine = 'Addetto alla conduzione di escavatori idraulici', riga_foglio = 13 where testo = 'ADDETTO ALLA CONDUZIONE DI ESCAVATORI IDRAULICI';
update corso_alias set testo_origine = 'Addetto alla conduzione di escavatori idraulici, caricatori frontali e terne', riga_foglio = 14 where testo = 'ADDETTO ALLA CONDUZIONE DI ESCAVATORI IDRAULICI, CARICATORI FRONTALI E TERNE';
update corso_alias set testo_origine = 'Addetto alla conduzione di gru a torre (Gru a rotazione in alto)', riga_foglio = 15 where testo = 'ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN ALTO)';
update corso_alias set testo_origine = 'Addetto alla conduzione di gru a torre (Gru a rotazione in basso e gru a rotazione in alto)', riga_foglio = 16 where testo = 'ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN BASSO E GRU A ROTAZIONE IN ALTO)';
update corso_alias set testo_origine = 'Addetto alla conduzione di gru a torre (Gru a rotazione in basso)', riga_foglio = 17 where testo = 'ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN BASSO)';
update corso_alias set testo_origine = 'Addetto alla conduzione di gru mobili - CORSO BASE (per gru mobili autocarrate e semoventi su ruote con braccio telescopico o tralicciato ed eventuale falcone fisso)', riga_foglio = 18 where testo = 'ADDETTO ALLA CONDUZIONE DI GRU MOBILI - CORSO BASE (PER GRU MOBILI AUTOCARRATE E SEMOVENTI SU RUOTE CON BRACCIO TELESCOPICO O TRALICCIATO ED EVENTUALE FALCONE FISSO)';
update corso_alias set testo_origine = 'Addetto alla conduzione di gru mobili - CORSO BASE e MODULO AGGIUNTIVO (per gru mobili su ruote con falcone telescopico o brandeggiabile)', riga_foglio = 19 where testo = 'ADDETTO ALLA CONDUZIONE DI GRU MOBILI - CORSO BASE E MODULO AGGIUNTIVO (PER GRU MOBILI SU RUOTE CON FALCONE TELESCOPICO O BRANDEGGIABILE)';
update corso_alias set testo_origine = 'Addetto alla conduzione di gru per autocarro', riga_foglio = 20 where testo = 'ADDETTO ALLA CONDUZIONE DI GRU PER AUTOCARRO';
update corso_alias set testo_origine = 'Addetto alla conduzione di pale caricatrici frontali', riga_foglio = 21 where testo = 'ADDETTO ALLA CONDUZIONE DI PALE CARICATRICI FRONTALI';
update corso_alias set testo_origine = 'Addetto alla conduzione di Piattaforme di Lavoro mobili Elevabili (PLE con e senza stabilizzatori)', riga_foglio = 22 where testo = 'ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE CON E SENZA STABILIZZATORI)';
update corso_alias set testo_origine = 'Addetto alla conduzione di Piattaforme di Lavoro mobili Elevabili (PLE con stabilizzatori)', riga_foglio = 23 where testo = 'ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE CON STABILIZZATORI)';
update corso_alias set testo_origine = 'Addetto alla conduzione di Piattaforme di Lavoro mobili Elevabili (PLE senza stabilizzatori)', riga_foglio = 24 where testo = 'ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE SENZA STABILIZZATORI)';
update corso_alias set testo_origine = 'Addetto alla conduzione di pompe per calcestruzzo', riga_foglio = 25 where testo = 'ADDETTO ALLA CONDUZIONE DI POMPE PER CALCESTRUZZO';
update corso_alias set testo_origine = 'Addetto alla conduzione di terne', riga_foglio = 26 where testo = 'ADDETTO ALLA CONDUZIONE DI TERNE';
update corso_alias set testo_origine = 'Addetto alla conduzione di trattori agricoli o forestali (Per trattori a cingoli e ruote)', riga_foglio = 27 where testo = 'ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A CINGOLI E RUOTE)';
update corso_alias set testo_origine = 'Addetto alla conduzione di trattori agricoli o forestali (Per trattori a cingoli)', riga_foglio = 28 where testo = 'ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A CINGOLI)';
update corso_alias set testo_origine = 'Addetto alla conduzione di trattori agricoli o forestali (Per trattori a ruote)', riga_foglio = 29 where testo = 'ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A RUOTE)';
update corso_alias set testo_origine = 'ADDETTO GESTIONE DELLA QUALITA''', riga_foglio = 30 where testo = 'ADDETTO GESTIONE DELLA QUALITA''';
update corso_alias set testo_origine = 'Addetto Lavori in Ambienti Sospetti di Presenza Amianto', riga_foglio = 31 where testo = 'ADDETTO LAVORI IN AMBIENTI SOSPETTI DI PRESENZA AMIANTO';
update corso_alias set testo_origine = 'Addetto Preposto Utilizzo della Segnaletica Stradale', riga_foglio = 32 where testo = 'ADDETTO PREPOSTO UTILIZZO DELLA SEGNALETICA STRADALE';
update corso_alias set testo_origine = 'Addetto prevenzione incendio, lotta antincendio e gestione dell’emergenza in attività a rischio d’incendio basso', riga_foglio = 33 where testo = 'ADDETTO PREVENZIONE INCENDIO, LOTTA ANTINCENDIO E GESTIONE DELL’EMERGENZA IN ATTIVITÀ A RISCHIO D’INCENDIO BASSO';
update corso_alias set testo_origine = 'Addetto prevenzione incendio, lotta antincendio e gestione dell’emergenza in attività a rischio d’incendio medio', riga_foglio = 34 where testo = 'ADDETTO PREVENZIONE INCENDIO, LOTTA ANTINCENDIO E GESTIONE DELL’EMERGENZA IN ATTIVITÀ A RISCHIO D’INCENDIO MEDIO';
update corso_alias set testo_origine = 'ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO A', riga_foglio = 35 where testo = 'ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO A';
update corso_alias set testo_origine = 'ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO B-C', riga_foglio = 36 where testo = 'ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO B-C';
update corso_alias set testo_origine = 'Addetto Utilizzo della Segnaletica Stradale', riga_foglio = 37 where testo = 'ADDETTO UTILIZZO DELLA SEGNALETICA STRADALE';
update corso_alias set testo_origine = 'Agg. Formazione per l''uso dei diisocianati - Livello generale, intermedio e avanzato', riga_foglio = 38 where testo = 'AGG. FORMAZIONE PER L''USO DEI DIISOCIANATI - LIVELLO GENERALE, INTERMEDIO E AVANZATO';
update corso_alias set testo_origine = 'Aggiornamento A.S.P.P. A.S.R. 2016', riga_foglio = 39 where testo = 'AGGIORNAMENTO A.S.P.P. A.S.R. 2016';
update corso_alias set testo_origine = 'Aggiornamento addetti alla conduzione carrelli elevatori semoventi con conducente a bordo (carrelli industriali semoventi, semoventi a braccio telescopico, carrelli/sollevatori/elevatori semoventi telescopici rotativi sollevamento carichi sospesi/persone)', riga_foglio = 40 where testo = 'AGGIORNAMENTO ADDETTI ALLA CONDUZIONE CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, SEMOVENTI A BRACCIO TELESCOPICO, CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI SOLLEVAMENTO CARICHI SOSPESI/PERSONE)';
update corso_alias set testo_origine = 'AGGIORNAMENTO ADDETTO AL MONTAGGIO, SMONTAGGIO, TRASFORMAZIONE DI PONTEGGI O PER PREPOSTI ALLA SORVEGLIANZA', riga_foglio = 41 where testo = 'AGGIORNAMENTO ADDETTO AL MONTAGGIO, SMONTAGGIO, TRASFORMAZIONE DI PONTEGGI O PER PREPOSTI ALLA SORVEGLIANZA';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di autoribaltabili a cingoli', riga_foglio = 42 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI AUTORIBALTABILI A CINGOLI';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di carrelli elevatori semoventi con conducente a bordo (Carrelli industriali semoventi)', riga_foglio = 43 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di carrelli elevatori semoventi con conducente a bordo (Carrelli industriali semoventi, carrelli semoventi a braccio telescopico, carrelli/sollevatori/elevatori semoventi telescopici rotativi)', riga_foglio = 44 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, CARRELLI SEMOVENTI A BRACCIO TELESCOPICO, CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di carrelli elevatori semoventi con conducente a bordo (Carrelli semoventi a braccio telescopico)', riga_foglio = 45 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI SEMOVENTI A BRACCIO TELESCOPICO)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di carrelli elevatori semoventi con conducente a bordo (Carrelli/sollevatori/elevatori semoventi telescopici rotativi)', riga_foglio = 46 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)';
update corso_alias set testo_origine = 'Aggiornamento addetto alla conduzione di Carroponte (Gru a Ponte)', riga_foglio = 47 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARROPONTE (GRU A PONTE)';
update corso_alias set testo_origine = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARROPONTE E GRU A BANDIERA', riga_foglio = 48 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI CARROPONTE E GRU A BANDIERA';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di escavatori a fune ', riga_foglio = 49 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI ESCAVATORI A FUNE';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di escavatori idraulici', riga_foglio = 50 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI ESCAVATORI IDRAULICI';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di escavatori idraulici, caricatori frontali e terne ', riga_foglio = 51 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI ESCAVATORI IDRAULICI, CARICATORI FRONTALI E TERNE';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di gru a torre (Gru a rotazione in alto)', riga_foglio = 52 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN ALTO)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di gru a torre (Gru a rotazione in basso e gru a rotazione in alto)', riga_foglio = 53 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN BASSO E GRU A ROTAZIONE IN ALTO)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di gru a torre (Gru a rotazione in basso)', riga_foglio = 54 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI GRU A TORRE (GRU A ROTAZIONE IN BASSO)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di gru mobili', riga_foglio = 55 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI GRU MOBILI';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di gru per autocarro', riga_foglio = 56 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI GRU PER AUTOCARRO';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di pale caricatrici frontali ', riga_foglio = 57 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI PALE CARICATRICI FRONTALI';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di Piattaforme di Lavoro mobili Elevabili (PLE con e senza stabilizzatori)', riga_foglio = 58 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE CON E SENZA STABILIZZATORI)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di Piattaforme di Lavoro mobili Elevabili (PLE con stabilizzatori)', riga_foglio = 59 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE CON STABILIZZATORI)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di Piattaforme di Lavoro mobili Elevabili (PLE senza stabilizzatori)', riga_foglio = 60 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE SENZA STABILIZZATORI)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di pompe per calcestruzzo', riga_foglio = 61 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI POMPE PER CALCESTRUZZO';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di terne ', riga_foglio = 62 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI TERNE';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di trattori agricoli o forestali (Per trattori a cingoli e ruote)', riga_foglio = 63 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A CINGOLI E RUOTE)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di trattori agricoli o forestali (Per trattori a cingoli)', riga_foglio = 64 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A CINGOLI)';
update corso_alias set testo_origine = 'Aggiornamento Addetto alla conduzione di trattori agricoli o forestali (Per trattori a ruote)', riga_foglio = 65 where testo = 'AGGIORNAMENTO ADDETTO ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI (PER TRATTORI A RUOTE)';
update corso_alias set testo_origine = 'Aggiornamento addetto antincendio rischio alto', riga_foglio = 66 where testo = 'AGGIORNAMENTO ADDETTO ANTINCENDIO RISCHIO ALTO';
update corso_alias set testo_origine = 'Aggiornamento Addetto Lavoratore e Preposto Utilizzo della Segnaletica Stradale', riga_foglio = 67 where testo = 'AGGIORNAMENTO ADDETTO LAVORATORE E PREPOSTO UTILIZZO DELLA SEGNALETICA STRADALE';
update corso_alias set testo_origine = 'Aggiornamento addetto prevenzione incendio, lotta antincendio e gestione dell’emergenza in attività a rischio d’incendio basso', riga_foglio = 68 where testo = 'AGGIORNAMENTO ADDETTO PREVENZIONE INCENDIO, LOTTA ANTINCENDIO E GESTIONE DELL’EMERGENZA IN ATTIVITÀ A RISCHIO D’INCENDIO BASSO';
update corso_alias set testo_origine = 'Aggiornamento addetto prevenzione incendio, lotta antincendio e gestione dell’emergenza in attività a rischio d’incendio medio', riga_foglio = 69 where testo = 'AGGIORNAMENTO ADDETTO PREVENZIONE INCENDIO, LOTTA ANTINCENDIO E GESTIONE DELL’EMERGENZA IN ATTIVITÀ A RISCHIO D’INCENDIO MEDIO';
update corso_alias set testo_origine = 'AGGIORNAMENTO ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO A', riga_foglio = 70 where testo = 'AGGIORNAMENTO ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO A';
update corso_alias set testo_origine = 'AGGIORNAMENTO ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO B-C', riga_foglio = 71 where testo = 'AGGIORNAMENTO ADDETTO PRIMO SOCCORSO AZIENDALE E GESTIONE DELLE EMERGENZE GRUPPO B-C';
update corso_alias set testo_origine = 'Aggiornamento ASPP', riga_foglio = 72 where testo = 'AGGIORNAMENTO ASPP';
update corso_alias set testo_origine = 'AGGIORNAMENTO BLS-D (Basic Life Support and Defibrillation) LAICO', riga_foglio = 73 where testo = 'AGGIORNAMENTO BLS-D (BASIC LIFE SUPPORT AND DEFIBRILLATION) LAICO';
update corso_alias set testo_origine = 'Aggiornamento Coordinatore della Sicurezza nei cantieri temporanei o mobili', riga_foglio = 74 where testo = 'AGGIORNAMENTO COORDINATORE DELLA SICUREZZA NEI CANTIERI TEMPORANEI O MOBILI';
update corso_alias set testo_origine = 'AGGIORNAMENTO COORDINATORI PER LA PROGETTAZIONE E PER L’ESECUZIONE DEI LAVORI', riga_foglio = 75 where testo = 'AGGIORNAMENTO COORDINATORI PER LA PROGETTAZIONE E PER L’ESECUZIONE DEI LAVORI';
update corso_alias set testo_origine = 'Aggiornamento Datore di Lavoro', riga_foglio = 76 where testo = 'AGGIORNAMENTO DATORE DI LAVORO';
update corso_alias set testo_origine = 'AGGIORNAMENTO DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP', riga_foglio = 77 where testo = 'AGGIORNAMENTO DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP';
update corso_alias set testo_origine = 'Aggiornamento Datore di Lavoro con Modulo aggiuntivo “Cantieri”', riga_foglio = 78 where testo = 'AGGIORNAMENTO DATORE DI LAVORO CON MODULO AGGIUNTIVO “CANTIERI”';
update corso_alias set testo_origine = 'Aggiornamento Dirigenti', riga_foglio = 79 where testo = 'AGGIORNAMENTO DIRIGENTI';
update corso_alias set testo_origine = 'Aggiornamento formazione dei lavoratori Rischio Alto', riga_foglio = 80 where testo = 'AGGIORNAMENTO FORMAZIONE DEI LAVORATORI RISCHIO ALTO';
update corso_alias set testo_origine = 'Aggiornamento formazione dei lavoratori Rischio Basso', riga_foglio = 81 where testo = 'AGGIORNAMENTO FORMAZIONE DEI LAVORATORI RISCHIO BASSO';
update corso_alias set testo_origine = 'Aggiornamento formazione dei lavoratori Rischio Medio', riga_foglio = 82 where testo = 'AGGIORNAMENTO FORMAZIONE DEI LAVORATORI RISCHIO MEDIO';
update corso_alias set testo_origine = 'Aggiornamento formazione lavori in quota e DPI 3°Cat. anticaduta', riga_foglio = 83 where testo = 'AGGIORNAMENTO FORMAZIONE LAVORI IN QUOTA E DPI 3°CAT. ANTICADUTA';
update corso_alias set testo_origine = 'AGGIORNAMENTO LAVORATORI - 6 ORE - EDILIZIA', riga_foglio = 84 where testo = 'AGGIORNAMENTO LAVORATORI - 6 ORE - EDILIZIA';
update corso_alias set testo_origine = 'Aggiornamento Lavoratori 6 ore', riga_foglio = 85 where testo = 'AGGIORNAMENTO LAVORATORI 6 ORE';
update corso_alias set testo_origine = 'Aggiornamento lavoratori addetti alla conduzione di caricatori per la movimentazione di materiali (CMM)', riga_foglio = 86 where testo = 'AGGIORNAMENTO LAVORATORI ADDETTI ALLA CONDUZIONE DI CARICATORI PER LA MOVIMENTAZIONE DI MATERIALI (CMM)';
update corso_alias set testo_origine = 'Aggiornamento lavoratori addetti alla conduzione di carriponte con comando in cabina', riga_foglio = 87 where testo = 'AGGIORNAMENTO LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO IN CABINA';
update corso_alias set testo_origine = 'Aggiornamento lavoratori addetti alla conduzione di carriponte con comando pensile/radiocomando', riga_foglio = 88 where testo = 'AGGIORNAMENTO LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO PENSILE/RADIOCOMANDO';
update corso_alias set testo_origine = 'Aggiornamento lavoratori addetti alla conduzione di carriponte con comando pensile/radiocomando e/o con comando in cabina', riga_foglio = 89 where testo = 'AGGIORNAMENTO LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO PENSILE/RADIOCOMANDO E/O CON COMANDO IN CABINA';
update corso_alias set testo_origine = 'Aggiornamento lavoratori addetti alla conduzione di macchina agricola raccoglifrutta (comunemente detta carro raccoglifrutta CRF)', riga_foglio = 90 where testo = 'AGGIORNAMENTO LAVORATORI ADDETTI ALLA CONDUZIONE DI MACCHINA AGRICOLA RACCOGLIFRUTTA (COMUNEMENTE DETTA CARRO RACCOGLIFRUTTA CRF)';
update corso_alias set testo_origine = 'AGGIORNAMENTO LAVORATORI PREPOSTI', riga_foglio = 91 where testo = 'AGGIORNAMENTO LAVORATORI PREPOSTI';
update corso_alias set testo_origine = 'AGGIORNAMENTO PARZIALE PER LAVORATORI', riga_foglio = 92 where testo = 'AGGIORNAMENTO PARZIALE PER LAVORATORI';
update corso_alias set testo_origine = 'AGGIORNAMENTO PARZIALE PER LAVORATORI - aperitivo', riga_foglio = 93 where testo = 'AGGIORNAMENTO PARZIALE PER LAVORATORI - APERITIVO';
update corso_alias set testo_origine = 'AGGIORNAMENTO PARZIALE PER R.L.S.', riga_foglio = 94 where testo = 'AGGIORNAMENTO PARZIALE PER R.L.S.';
update corso_alias set testo_origine = 'AGGIORNAMENTO PARZIALE PER RLS', riga_foglio = 95 where testo = 'AGGIORNAMENTO PARZIALE PER RLS';
update corso_alias set testo_origine = 'AGGIORNAMENTO PARZIALE PER RSPP DATORE DI LAVORO RISCHIO ALTO', riga_foglio = 96 where testo = 'AGGIORNAMENTO PARZIALE PER RSPP DATORE DI LAVORO RISCHIO ALTO';
update corso_alias set testo_origine = 'Aggiornamento per lavoratori, datori di lavoro e lavoratori autonomi che operano in ambienti sospetti di inquinamento o confinati', riga_foglio = 97 where testo = 'AGGIORNAMENTO PER LAVORATORI, DATORI DI LAVORO E LAVORATORI AUTONOMI CHE OPERANO IN AMBIENTI SOSPETTI DI INQUINAMENTO O CONFINATI';
update corso_alias set testo_origine = 'Aggiornamento PES E PAV Operatori su Quadri Elettrici', riga_foglio = 98 where testo = 'AGGIORNAMENTO PES E PAV OPERATORI SU QUADRI ELETTRICI';
update corso_alias set testo_origine = 'Aggiornamento R.L.S. 4 ore', riga_foglio = 99 where testo = 'AGGIORNAMENTO R.L.S. 4 ORE';
update corso_alias set testo_origine = 'Aggiornamento R.L.S. 8 ore', riga_foglio = 100 where testo = 'AGGIORNAMENTO R.L.S. 8 ORE';
update corso_alias set testo_origine = 'Aggiornamento R.S.P.P. A.S.R. 2016', riga_foglio = 101 where testo = 'AGGIORNAMENTO R.S.P.P. A.S.R. 2016';
update corso_alias set testo_origine = 'AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO RISCHIO ALTO', riga_foglio = 102 where testo = 'AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO RISCHIO ALTO';
update corso_alias set testo_origine = 'AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO RISCHIO BASSO', riga_foglio = 103 where testo = 'AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO RISCHIO BASSO';
update corso_alias set testo_origine = 'AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO RISCHIO MEDIO', riga_foglio = 104 where testo = 'AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO RISCHIO MEDIO';
update corso_alias set testo_origine = 'AGGIORNAMENTO R.SP.P./A.S.P.P. - MODULO B', riga_foglio = 105 where testo = 'AGGIORNAMENTO R.SP.P./A.S.P.P. - MODULO B';
update corso_alias set testo_origine = 'Aggiornamento RSPP', riga_foglio = 106 where testo = 'AGGIORNAMENTO RSPP';
update corso_alias set testo_origine = 'Appalti e Subappalti', riga_foglio = 107 where testo = 'APPALTI E SUBAPPALTI';
update corso_alias set testo_origine = 'BLS-D (Basic Life Support and Defibrillation) (laico)', riga_foglio = 108 where testo = 'BLS-D (BASIC LIFE SUPPORT AND DEFIBRILLATION) (LAICO)';
update corso_alias set testo_origine = 'BLS-D (Basic Life Support and Defibrillation) LAICO', riga_foglio = 109 where testo = 'BLS-D (BASIC LIFE SUPPORT AND DEFIBRILLATION) LAICO';
update corso_alias set testo_origine = 'BLS-D (BASIC LIFE SUPPORT AND DEFIBRILLATION) PER SANITARI', riga_foglio = 110 where testo = 'BLS-D (BASIC LIFE SUPPORT AND DEFIBRILLATION) PER SANITARI';
update corso_alias set testo_origine = 'Coordinatore della Sicurezza nei cantieri temporanei o mobili', riga_foglio = 111 where testo = 'COORDINATORE DELLA SICUREZZA NEI CANTIERI TEMPORANEI O MOBILI';
update corso_alias set testo_origine = 'CORSO ABC RIFIUTI', riga_foglio = 112 where testo = 'CORSO ABC RIFIUTI';
update corso_alias set testo_origine = 'CORSO ADEMPIMENTI E OBBLIGHI ATTUATIVI PREVISTI DAL REGOLAMENTO PRIVACY UE 2016/679 (GDPR)', riga_foglio = 113 where testo = 'CORSO ADEMPIMENTI E OBBLIGHI ATTUATIVI PREVISTI DAL REGOLAMENTO PRIVACY UE 2016/679 (GDPR)';
update corso_alias set testo_origine = 'Corso Antincendio Rischio Alto', riga_foglio = 114 where testo = 'CORSO ANTINCENDIO RISCHIO ALTO';
update corso_alias set testo_origine = 'Corso di aggiornamento antincendio per addetti antincendio in attività di livello 1', riga_foglio = 115 where testo = 'CORSO DI AGGIORNAMENTO ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 1';
update corso_alias set testo_origine = 'Corso di aggiornamento antincendio per addetti antincendio in attività di livello 2', riga_foglio = 116 where testo = 'CORSO DI AGGIORNAMENTO ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 2';
update corso_alias set testo_origine = 'Corso di aggiornamento antincendio per addetti antincendio in attività di livello 3', riga_foglio = 117 where testo = 'CORSO DI AGGIORNAMENTO ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 3';
update corso_alias set testo_origine = 'CORSO DI AGGIORNAMENTO DIRIGENTE', riga_foglio = 118 where testo = 'CORSO DI AGGIORNAMENTO DIRIGENTE';
update corso_alias set testo_origine = 'CORSO DI AGGIORNAMENTO DIRIGENTE  con modulo aggiuntivo cantieri', riga_foglio = 119 where testo = 'CORSO DI AGGIORNAMENTO DIRIGENTE CON MODULO AGGIUNTIVO CANTIERI';
update corso_alias set testo_origine = 'CORSO DI AGGIORNAMENTO PER ADDETTO ALLA CONDUZIONE DI CARROPONTE', riga_foglio = 120 where testo = 'CORSO DI AGGIORNAMENTO PER ADDETTO ALLA CONDUZIONE DI CARROPONTE';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di autoribaltabili a cingoli', riga_foglio = 121 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI AUTORIBALTABILI A CINGOLI';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di carrelli elevatori semoventi con conducente a bordo (carrelli industriali semoventi)', riga_foglio = 122 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI)';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di carrelli elevatori semoventi con conducente a bordo (carrelli industriali semoventi, carrelli semoventi a braccio telescopico e carrelli/sollevatori/elevatori semoventi telescopici rotativi)', riga_foglio = 123 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, CARRELLI SEMOVENTI A BRACCIO TELESCOPICO E CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di carrelli elevatori semoventi con conducente a bordo (carrelli semoventi a braccio telescopico)', riga_foglio = 124 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI SEMOVENTI A BRACCIO TELESCOPICO)';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di carrelli elevatori semoventi con conducente a bordo (carrelli/sollevatori/elevatori semoventi telescopici rotativi)', riga_foglio = 125 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di escavatori a fune', riga_foglio = 126 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI A FUNE';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di escavatori idraulici', riga_foglio = 127 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI IDRAULICI';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di escavatori idraulici, caricatori frontali e terne', riga_foglio = 128 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI IDRAULICI, CARICATORI FRONTALI E TERNE';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di gru a torre a rotazione in alto', riga_foglio = 129 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN ALTO';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di gru a torre a rotazione in basso', riga_foglio = 130 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN BASSO';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di gru a torre a rotazione in basso e in alto', riga_foglio = 131 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN BASSO E IN ALTO';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di gru mobili', riga_foglio = 132 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU MOBILI';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di gru per autocarro', riga_foglio = 133 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU PER AUTOCARRO';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di pale caricatrici frontali', riga_foglio = 134 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PALE CARICATRICI FRONTALI';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di piattaforme di lavoro mobili elevabili (PLE) con e senza stabilizzatori', riga_foglio = 135 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) CON E SENZA STABILIZZATORI';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di piattaforme di lavoro mobili elevabili (PLE) senza stabilizzatori', riga_foglio = 136 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) SENZA STABILIZZATORI';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di piattaforme di lavoro mobili elevabili (PLE) su stabilizzatori', riga_foglio = 137 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) SU STABILIZZATORI';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di pompe per calcestruzzo', riga_foglio = 138 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI POMPE PER CALCESTRUZZO';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di terne', riga_foglio = 139 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TERNE';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di trattori agricoli o forestali a cingoli', riga_foglio = 140 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A CINGOLI';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di trattori agricoli o forestali a ruote', riga_foglio = 141 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A RUOTE';
update corso_alias set testo_origine = 'Corso di aggiornamento per lavoratori addetti alla conduzione di trattori agricoli o forestali a ruote e a cingoli', riga_foglio = 142 where testo = 'CORSO DI AGGIORNAMENTO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A RUOTE E A CINGOLI';
update corso_alias set testo_origine = 'CORSO DI AGGIORNAMENTO PER PREPOSTI', riga_foglio = 143 where testo = 'CORSO DI AGGIORNAMENTO PER PREPOSTI';
update corso_alias set testo_origine = 'Corso di formazione antincendio per addetti antincendio in attività di livello 1', riga_foglio = 144 where testo = 'CORSO DI FORMAZIONE ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 1';
update corso_alias set testo_origine = 'Corso di formazione antincendio per addetti antincendio in attività di livello 2', riga_foglio = 145 where testo = 'CORSO DI FORMAZIONE ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 2';
update corso_alias set testo_origine = 'Corso di formazione antincendio per addetti antincendio in attività di livello 3', riga_foglio = 146 where testo = 'CORSO DI FORMAZIONE ANTINCENDIO PER ADDETTI ANTINCENDIO IN ATTIVITÀ DI LIVELLO 3';
update corso_alias set testo_origine = 'Corso di formazione lavori in quota', riga_foglio = 147 where testo = 'CORSO DI FORMAZIONE LAVORI IN QUOTA';
update corso_alias set testo_origine = 'CORSO DI FORMAZIONE LAVORI IN QUOTA E DPI 3* CAT. ANTICADUTA + SCALE/TRABATTELLO', riga_foglio = 148 where testo = 'CORSO DI FORMAZIONE LAVORI IN QUOTA E DPI 3* CAT. ANTICADUTA + SCALE/TRABATTELLO';
update corso_alias set testo_origine = 'Corso di formazione lavori in quota e DPI 3°Cat. anticaduta', riga_foglio = 149 where testo = 'CORSO DI FORMAZIONE LAVORI IN QUOTA E DPI 3°CAT. ANTICADUTA';
update corso_alias set testo_origine = 'CORSO DI FORMAZIONE PER I COORDINATORI PER LA PROGETTAZIONE E PER L’ESECUZIONE DEI LAVORI', riga_foglio = 150 where testo = 'CORSO DI FORMAZIONE PER I COORDINATORI PER LA PROGETTAZIONE E PER L’ESECUZIONE DEI LAVORI';
update corso_alias set testo_origine = 'CORSO DI FORMAZIONE PER PREPOSTI', riga_foglio = 151 where testo = 'CORSO DI FORMAZIONE PER PREPOSTI';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per addetti alla conduzione di carrelli elevatori semoventi con conducente a bordo (carrelli industriali semoventi, semoventi a braccio telescopico e carrelli/sollevatori/elevatori semoventi telescopici rotativi)', riga_foglio = 152 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, SEMOVENTI A BRACCIO TELESCOPICO E CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di autoribaltabili a cingoli', riga_foglio = 153 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI AUTORIBALTABILI A CINGOLI';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di caricatori per la movimentazione di materiali (CMM)', riga_foglio = 154 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARICATORI PER LA MOVIMENTAZIONE DI MATERIALI (CMM)';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di carrelli elevatori semoventi con conducente a bordo (carrelli industriali semoventi)', riga_foglio = 155 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI)';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di carrelli elevatori semoventi con conducente a bordo (carrelli semoventi a braccio telescopico)', riga_foglio = 156 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI SEMOVENTI A BRACCIO TELESCOPICO)';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di carrelli elevatori semoventi con conducente a bordo (carrelli/sollevatori/elevatori semoventi telescopici rotativi)', riga_foglio = 157 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI)';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di carriponte con comando in cabina', riga_foglio = 158 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO IN CABINA';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di carriponte con comando pensile/radiocomando', riga_foglio = 159 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO PENSILE/RADIOCOMANDO';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di carriponte con comando pensile/radiocomando e/o con comando in cabina', riga_foglio = 160 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRIPONTE CON COMANDO PENSILE/RADIOCOMANDO E/O CON COMANDO IN CABINA';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di escavatori a fune', riga_foglio = 161 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI A FUNE';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di escavatori idraulici', riga_foglio = 162 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI IDRAULICI';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di escavatori idraulici, caricatori frontali e terne', riga_foglio = 163 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI ESCAVATORI IDRAULICI, CARICATORI FRONTALI E TERNE';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di gru a torre a rotazione in alto', riga_foglio = 164 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN ALTO';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di gru a torre a rotazione in basso', riga_foglio = 165 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN BASSO';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di gru a torre a rotazione in basso e in alto', riga_foglio = 166 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU A TORRE A ROTAZIONE IN BASSO E IN ALTO';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di gru mobili-Modulo Base e Modulo Aggiuntivo per le gru mobili su ruote con falcone telescopico o brandeggiabile', riga_foglio = 167 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU MOBILI-MODULO BASE E MODULO AGGIUNTIVO PER LE GRU MOBILI SU RUOTE CON FALCONE TELESCOPICO O BRANDEGGIABILE';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di gru mobili-Modulo Base per gru mobili autocarrate e semoventi su ruote con braccio telescopico o tralicciato ed eventuale falcone fisso', riga_foglio = 168 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU MOBILI-MODULO BASE PER GRU MOBILI AUTOCARRATE E SEMOVENTI SU RUOTE CON BRACCIO TELESCOPICO O TRALICCIATO ED EVENTUALE FALCONE FISSO';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di gru per autocarro', riga_foglio = 169 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI GRU PER AUTOCARRO';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di macchina agricola raccoglifrutta (comunemente detta carro raccoglifrutta CRF)', riga_foglio = 170 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI MACCHINA AGRICOLA RACCOGLIFRUTTA (COMUNEMENTE DETTA CARRO RACCOGLIFRUTTA CRF)';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di pale caricatrici frontali', riga_foglio = 171 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PALE CARICATRICI FRONTALI';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di piattaforme di lavoro mobili elevabili (PLE) con e senza stabilizzatori', riga_foglio = 172 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) CON E SENZA STABILIZZATORI';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di piattaforme di lavoro mobili elevabili (PLE) senza stabilizzatori', riga_foglio = 173 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) SENZA STABILIZZATORI';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di piattaforme di lavoro mobili elevabili (PLE) su stabilizzatori', riga_foglio = 174 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE) SU STABILIZZATORI';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di pompe per calcestruzzo', riga_foglio = 175 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI POMPE PER CALCESTRUZZO';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di terne', riga_foglio = 176 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TERNE';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di trattori agricoli o forestali a cingoli', riga_foglio = 177 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A CINGOLI';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di trattori agricoli o forestali a ruote', riga_foglio = 178 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A RUOTE';
update corso_alias set testo_origine = 'Corso di formazione teorico-pratico per lavoratori addetti alla conduzione di trattori agricoli o forestali a ruote e a cingoli', riga_foglio = 179 where testo = 'CORSO DI FORMAZIONE TEORICO-PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI TRATTORI AGRICOLI O FORESTALI A RUOTE E A CINGOLI';
update corso_alias set testo_origine = 'CORSO PER ADDETTI  AI LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO', riga_foglio = 180 where testo = 'CORSO PER ADDETTI AI LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO';
update corso_alias set testo_origine = 'CORSO PER ADDETTI  AI LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO- ASR 2025', riga_foglio = 181 where testo = 'CORSO PER ADDETTI AI LAVORI IN SPAZI CONFINATI E SOSPETTI DI INQUINAMENTO- ASR 2025';
update corso_alias set testo_origine = 'CORSO PER ADDETTI AI LAVORI IN QUOTA E ALL''UTILIZZO DI SCALE PORTATILI E FISSE', riga_foglio = 182 where testo = 'CORSO PER ADDETTI AI LAVORI IN QUOTA E ALL''UTILIZZO DI SCALE PORTATILI E FISSE';
update corso_alias set testo_origine = 'CORSO PER ADDETTO ALLA CONDUZIONE DI CARROPONTE', riga_foglio = 183 where testo = 'CORSO PER ADDETTO ALLA CONDUZIONE DI CARROPONTE';
update corso_alias set testo_origine = 'Corso per Addetto alla conduzione di Carroponte (Gru a Ponte)', riga_foglio = 184 where testo = 'CORSO PER ADDETTO ALLA CONDUZIONE DI CARROPONTE (GRU A PONTE)';
update corso_alias set testo_origine = 'CORSO PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP MODULO COMUNE', riga_foglio = 185 where testo = 'CORSO PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP MODULO COMUNE';
update corso_alias set testo_origine = 'CORSO PER DIRIGENTE', riga_foglio = 186 where testo = 'CORSO PER DIRIGENTE';
update corso_alias set testo_origine = 'CORSO PER DIRIGENTE con modulo aggiuntivo cantieri', riga_foglio = 187 where testo = 'CORSO PER DIRIGENTE CON MODULO AGGIUNTIVO CANTIERI';
update corso_alias set testo_origine = 'Corso per lavoratori, datori di lavoro e lavoratori autonomi che operano in ambienti sospetti di inquinamento o confinati', riga_foglio = 188 where testo = 'CORSO PER LAVORATORI, DATORI DI LAVORO E LAVORATORI AUTONOMI CHE OPERANO IN AMBIENTI SOSPETTI DI INQUINAMENTO O CONFINATI';
update corso_alias set testo_origine = 'Corso per patentino fitosanitari (primo rilascio)', riga_foglio = 189 where testo = 'CORSO PER PATENTINO FITOSANITARI (PRIMO RILASCIO)';
update corso_alias set testo_origine = 'CORSO PES, PAV, PEI PER ADDETTI AI LAVORI ELETTRICI – NUOVA NORMA CEI 11-27 EDIZIONE 2021', riga_foglio = 190 where testo = 'CORSO PES, PAV, PEI PER ADDETTI AI LAVORI ELETTRICI – NUOVA NORMA CEI 11-27 EDIZIONE 2021';
update corso_alias set testo_origine = 'Corso rinnovo del patentino fitosanitari', riga_foglio = 191 where testo = 'CORSO RINNOVO DEL PATENTINO FITOSANITARI';
update corso_alias set testo_origine = 'CORSO RSPP / ASPP MODULO A', riga_foglio = 192 where testo = 'CORSO RSPP / ASPP MODULO A';
update corso_alias set testo_origine = 'CORSO RSPP / ASPP MODULO B COMUNE', riga_foglio = 193 where testo = 'CORSO RSPP / ASPP MODULO B COMUNE';
update corso_alias set testo_origine = 'CORSO RSPP MODULO C', riga_foglio = 194 where testo = 'CORSO RSPP MODULO C';
update corso_alias set testo_origine = 'CORSO TEORICO E PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI DI TIPO TRANSPALLET', riga_foglio = 195 where testo = 'CORSO TEORICO E PRATICO PER LAVORATORI ADDETTI ALLA CONDUZIONE DI CARRELLI ELEVATORI DI TIPO TRANSPALLET';
update corso_alias set testo_origine = 'Datore di Lavoro', riga_foglio = 196 where testo = 'DATORE DI LAVORO';
update corso_alias set testo_origine = 'Datore di Lavoro con Modulo aggiuntivo “Cantieri”', riga_foglio = 197 where testo = 'DATORE DI LAVORO CON MODULO AGGIUNTIVO “CANTIERI”';
update corso_alias set testo_origine = 'Dirigenti', riga_foglio = 198 where testo = 'DIRIGENTI';
update corso_alias set testo_origine = 'ESECUTORE BLSD - CATEGORIA B', riga_foglio = 199 where testo = 'ESECUTORE BLSD - CATEGORIA B';
update corso_alias set testo_origine = 'Formazione addetti alla conduzione carrelli elevatori semoventi con conducente a bordo (carrelli industriali semoventi, semoventi a braccio telescopico, carrelli/sollevatori/elevatori semoventi telescopici rotativi sollevamento carichi sospesi/persone)', riga_foglio = 200 where testo = 'FORMAZIONE ADDETTI ALLA CONDUZIONE CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI, SEMOVENTI A BRACCIO TELESCOPICO, CARRELLI/SOLLEVATORI/ELEVATORI SEMOVENTI TELESCOPICI ROTATIVI SOLLEVAMENTO CARICHI SOSPESI/PERSONE)';
update corso_alias set testo_origine = 'FORMAZIONE ADDETTO ALLA CONDUZIONE DI CARROPONTE (GRU CARROPONTE/ GRU A CAVALLETTO CON COMANDO PENSILE/RADIOCOMANDATO)', riga_foglio = 201 where testo = 'FORMAZIONE ADDETTO ALLA CONDUZIONE DI CARROPONTE (GRU CARROPONTE/ GRU A CAVALLETTO CON COMANDO PENSILE/RADIOCOMANDATO)';
update corso_alias set testo_origine = 'Formazione dei lavoratori (generale)', riga_foglio = 202 where testo = 'FORMAZIONE DEI LAVORATORI (GENERALE)';
update corso_alias set testo_origine = 'Formazione dei lavoratori Rischio Basso', riga_foglio = 203 where testo = 'FORMAZIONE DEI LAVORATORI RISCHIO BASSO';
update corso_alias set testo_origine = 'Formazione Lavoratori Rischio Alto', riga_foglio = 204 where testo = 'FORMAZIONE LAVORATORI RISCHIO ALTO';
update corso_alias set testo_origine = 'Formazione lavoratori Rischio Alto -  Specifica', riga_foglio = 205 where testo = 'FORMAZIONE LAVORATORI RISCHIO ALTO - SPECIFICA';
update corso_alias set testo_origine = 'Formazione Lavoratori Rischio Basso', riga_foglio = 206 where testo = 'FORMAZIONE LAVORATORI RISCHIO BASSO';
update corso_alias set testo_origine = 'Formazione lavoratori Rischio Basso -  Specifica', riga_foglio = 207 where testo = 'FORMAZIONE LAVORATORI RISCHIO BASSO - SPECIFICA';
update corso_alias set testo_origine = 'Formazione Lavoratori Rischio Medio', riga_foglio = 208 where testo = 'FORMAZIONE LAVORATORI RISCHIO MEDIO';
update corso_alias set testo_origine = 'Formazione lavoratori Rischio Medio -  Specifica', riga_foglio = 209 where testo = 'FORMAZIONE LAVORATORI RISCHIO MEDIO - SPECIFICA';
update corso_alias set testo_origine = 'FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI', riga_foglio = 210 where testo = 'FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI';
update corso_alias set testo_origine = 'FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI - BIENNALE', riga_foglio = 211 where testo = 'FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI - BIENNALE';
update corso_alias set testo_origine = 'FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI_BIENNALE', riga_foglio = 212 where testo = 'FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI_BIENNALE';
update corso_alias set testo_origine = 'Formazione per l''uso dei diisocianati - Livello generale, intermedio e avanzato', riga_foglio = 213 where testo = 'FORMAZIONE PER L''USO DEI DIISOCIANATI - LIVELLO GENERALE, INTERMEDIO E AVANZATO';
update corso_alias set testo_origine = 'Formazione per l''uso dei diisocianati: Livello generale, intermedio e avanzato', riga_foglio = 214 where testo = 'FORMAZIONE PER L''USO DEI DIISOCIANATI: LIVELLO GENERALE, INTERMEDIO E AVANZATO';
update corso_alias set testo_origine = 'FORMAZIONE SPECIFICA RISCHIO ALTO PARZIALE 6H 1\2', riga_foglio = 215 where testo = 'FORMAZIONE SPECIFICA RISCHIO ALTO PARZIALE 6H 1\2';
update corso_alias set testo_origine = 'FORMAZIONE SPECIFICA RISCHIO ALTO, PARZIALE 6H 2/2', riga_foglio = 216 where testo = 'FORMAZIONE SPECIFICA RISCHIO ALTO, PARZIALE 6H 2/2';
update corso_alias set testo_origine = 'IGIENE ALIMENTI', riga_foglio = 217 where testo = 'IGIENE ALIMENTI';
update corso_alias set testo_origine = 'integrazione Addetto alla conduzione di Piattaforme di lavoro mobili Elevabili (Ple con stabilizzatori)', riga_foglio = 218 where testo = 'INTEGRAZIONE ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE CON STABILIZZATORI)';
update corso_alias set testo_origine = 'Integrazione Addetto alla conduzione di Piattaforme di Lavoro mobili Elevabili (PLE senza stabilizzatori)', riga_foglio = 219 where testo = 'INTEGRAZIONE ADDETTO ALLA CONDUZIONE DI PIATTAFORME DI LAVORO MOBILI ELEVABILI (PLE SENZA STABILIZZATORI)';
update corso_alias set testo_origine = 'INTEGRAZIONE FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI', riga_foglio = 220 where testo = 'INTEGRAZIONE FORMAZIONE PARTICOLARE AGGIUNTIVA PREPOSTI';
update corso_alias set testo_origine = 'Integrazione formazione specifica lavoratori - rischio alto', riga_foglio = 221 where testo = 'INTEGRAZIONE FORMAZIONE SPECIFICA LAVORATORI - RISCHIO ALTO';
update corso_alias set testo_origine = 'Integrazione formazione specifica lavoratori- rischio alto', riga_foglio = 222 where testo = 'INTEGRAZIONE FORMAZIONE SPECIFICA LAVORATORI- RISCHIO ALTO';
update corso_alias set testo_origine = 'Integrazione formazione specifica lavoratori-rischio alto', riga_foglio = 223 where testo = 'INTEGRAZIONE FORMAZIONE SPECIFICA LAVORATORI-RISCHIO ALTO';
update corso_alias set testo_origine = 'Integrazione formazione specifica lavoratori-Rischio Medio', riga_foglio = 224 where testo = 'INTEGRAZIONE FORMAZIONE SPECIFICA LAVORATORI-RISCHIO MEDIO';
update corso_alias set testo_origine = 'INTEGRAZIONE R.S.P.P. DATORE DI LAVORO MODULO 3 E 4 - RISCHIO ALTO', riga_foglio = 225 where testo = 'INTEGRAZIONE R.S.P.P. DATORE DI LAVORO MODULO 3 E 4 - RISCHIO ALTO';
update corso_alias set testo_origine = 'INTEGRAZIONE R.S.P.P. DATORE DI LAVORO MODULO 3 E 4 - RISCHIO BASSO', riga_foglio = 226 where testo = 'INTEGRAZIONE R.S.P.P. DATORE DI LAVORO MODULO 3 E 4 - RISCHIO BASSO';
update corso_alias set testo_origine = 'INTEGRAZIONE R.S.P.P. DATORE DI LAVORO MODULO 3 E 4 - RISCHIO MEDIO', riga_foglio = 227 where testo = 'INTEGRAZIONE R.S.P.P. DATORE DI LAVORO MODULO 3 E 4 - RISCHIO MEDIO';
update corso_alias set testo_origine = 'Lavoratori e Preposti addetti al montaggio,
smontaggio e trasformazione di ponteggi, uso DPI anticaduta', riga_foglio = 228 where testo = 'LAVORATORI E PREPOSTI ADDETTI AL MONTAGGIO, SMONTAGGIO E TRASFORMAZIONE DI PONTEGGI, USO DPI ANTICADUTA';
update corso_alias set testo_origine = 'Lavori in Ambienti Confinati (Aggiornamento Coordinatore Sicurezza)', riga_foglio = 229 where testo = 'LAVORI IN AMBIENTI CONFINATI (AGGIORNAMENTO COORDINATORE SICUREZZA)';
update corso_alias set testo_origine = 'Lavori in Ambienti Confinati (Aggiornamento Lavoratori)', riga_foglio = 230 where testo = 'LAVORI IN AMBIENTI CONFINATI (AGGIORNAMENTO LAVORATORI)';
update corso_alias set testo_origine = 'Lavori in Ambienti Confinati (Aggiornamento Preposto)', riga_foglio = 231 where testo = 'LAVORI IN AMBIENTI CONFINATI (AGGIORNAMENTO PREPOSTO)';
update corso_alias set testo_origine = 'Lavori in Ambienti Confinati (Aggiornamento R.S.P.P. Datore di Lavoro)', riga_foglio = 232 where testo = 'LAVORI IN AMBIENTI CONFINATI (AGGIORNAMENTO R.S.P.P. DATORE DI LAVORO)';
update corso_alias set testo_origine = 'Lavori in Ambienti Confinati (Aggiornamento R.S.P.P. Modulo B)', riga_foglio = 233 where testo = 'LAVORI IN AMBIENTI CONFINATI (AGGIORNAMENTO R.S.P.P. MODULO B)';
update corso_alias set testo_origine = 'Modulo Aggiuntivo “Cantieri” per Datori di lavoro', riga_foglio = 234 where testo = 'MODULO AGGIUNTIVO “CANTIERI” PER DATORI DI LAVORO';
update corso_alias set testo_origine = 'MODULO AGGIUNTIVO “CANTIERI” PER DIRIGENTE', riga_foglio = 235 where testo = 'MODULO AGGIUNTIVO “CANTIERI” PER DIRIGENTE';
update corso_alias set testo_origine = 'Modulo B di specializzazione SP1: Agricoltura – Silvicoltura - Zootecnia per RSPP/ASPP', riga_foglio = 236 where testo = 'MODULO B DI SPECIALIZZAZIONE SP1: AGRICOLTURA – SILVICOLTURA - ZOOTECNIA PER RSPP/ASPP';
update corso_alias set testo_origine = 'Modulo B di specializzazione SP2: Pesca per RSPP/ASPP', riga_foglio = 237 where testo = 'MODULO B DI SPECIALIZZAZIONE SP2: PESCA PER RSPP/ASPP';
update corso_alias set testo_origine = 'Modulo B di specializzazione SP3: Costruzioni per RSPP/ASPP', riga_foglio = 238 where testo = 'MODULO B DI SPECIALIZZAZIONE SP3: COSTRUZIONI PER RSPP/ASPP';
update corso_alias set testo_origine = 'Modulo B di specializzazione SP4: Sanità residenziale per RSPP/ASPP', riga_foglio = 239 where testo = 'MODULO B DI SPECIALIZZAZIONE SP4: SANITÀ RESIDENZIALE PER RSPP/ASPP';
update corso_alias set testo_origine = 'Modulo B di specializzazione SP5: Chimico - Petrolchimico per RSPP/ASPP', riga_foglio = 240 where testo = 'MODULO B DI SPECIALIZZAZIONE SP5: CHIMICO - PETROLCHIMICO PER RSPP/ASPP';
update corso_alias set testo_origine = 'Modulo integrativo 1: Agricoltura – Silvicoltura - Zootecnia per Datore di Lavoro che svolge i compiti di RSPP', riga_foglio = 241 where testo = 'MODULO INTEGRATIVO 1: AGRICOLTURA – SILVICOLTURA - ZOOTECNIA PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP';
update corso_alias set testo_origine = 'Modulo integrativo 2: Pesca per Datore di Lavoro che svolge i compiti di RSPP', riga_foglio = 242 where testo = 'MODULO INTEGRATIVO 2: PESCA PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP';
update corso_alias set testo_origine = 'Modulo integrativo 3: Costruzioni  per Datore di Lavoro che svolge i compiti di RSPP', riga_foglio = 243 where testo = 'MODULO INTEGRATIVO 3: COSTRUZIONI PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP';
update corso_alias set testo_origine = 'Modulo integrativo 4: Chimico - Petrolchimico per Datore di Lavoro che svolge i compiti di RSPP', riga_foglio = 244 where testo = 'MODULO INTEGRATIVO 4: CHIMICO - PETROLCHIMICO PER DATORE DI LAVORO CHE SVOLGE I COMPITI DI RSPP';
update corso_alias set testo_origine = 'MV 200 - Rodiggio', riga_foglio = 245 where testo = 'MV 200 - RODIGGIO';
update corso_alias set testo_origine = 'MV 210 - Carrelli', riga_foglio = 246 where testo = 'MV 210 - CARRELLI';
update corso_alias set testo_origine = 'MV 220 - Impianto Pneumatico e Freno', riga_foglio = 247 where testo = 'MV 220 - IMPIANTO PNEUMATICO E FRENO';
update corso_alias set testo_origine = 'MV 230 - Apparecchiature di bordo per lo sicurezza dello condotta (IPE)', riga_foglio = 248 where testo = 'MV 230 - APPARECCHIATURE DI BORDO PER LO SICUREZZA DELLO CONDOTTA (IPE)';
update corso_alias set testo_origine = 'MV 240 - Organi di aggancio e repulsione', riga_foglio = 249 where testo = 'MV 240 - ORGANI DI AGGANCIO E REPULSIONE';
update corso_alias set testo_origine = 'MV 250 - Impiantistica Elettrica ed elettronica (di base, di potenza, di segnale)', riga_foglio = 250 where testo = 'MV 250 - IMPIANTISTICA ELETTRICA ED ELETTRONICA (DI BASE, DI POTENZA, DI SEGNALE)';
update corso_alias set testo_origine = 'MV 260 - Porte', riga_foglio = 251 where testo = 'MV 260 - PORTE';
update corso_alias set testo_origine = 'MV 270 - Telaio e Cassa (Dispositivi di blocco parti mobili)', riga_foglio = 252 where testo = 'MV 270 - TELAIO E CASSA (DISPOSITIVI DI BLOCCO PARTI MOBILI)';
update corso_alias set testo_origine = 'MV 280 - Impianto Antincendio', riga_foglio = 253 where testo = 'MV 280 - IMPIANTO ANTINCENDIO';
update corso_alias set testo_origine = 'PEI, PES E PAV Operatori su Quadri Elettrici', riga_foglio = 254 where testo = 'PEI, PES E PAV OPERATORI SU QUADRI ELETTRICI';
update corso_alias set testo_origine = 'Pre ASR_2015_ Addetto alla conduzione di carrelli elevatori semoventi con conducente a bordo (Carrelli industriali semoventi)', riga_foglio = 255 where testo = 'PRE ASR_2015_ ADDETTO ALLA CONDUZIONE DI CARRELLI ELEVATORI SEMOVENTI CON CONDUCENTE A BORDO (CARRELLI INDUSTRIALI SEMOVENTI)';
update corso_alias set testo_origine = 'QUALIFICA SALDATORE', riga_foglio = 256 where testo = 'QUALIFICA SALDATORE';
update corso_alias set testo_origine = 'R.L.S.', riga_foglio = 257 where testo = 'R.L.S.';
update corso_alias set testo_origine = 'R.S.P.P. - Modulo C - A.S.R. 2016', riga_foglio = 258 where testo = 'R.S.P.P. - MODULO C - A.S.R. 2016';
update corso_alias set testo_origine = 'R.S.P.P. / A.S.P.P. - Modulo A - A.S.R. 2016', riga_foglio = 259 where testo = 'R.S.P.P. / A.S.P.P. - MODULO A - A.S.R. 2016';
update corso_alias set testo_origine = 'R.S.P.P. / A.S.P.P.  modulo B COMUNE', riga_foglio = 260 where testo = 'R.S.P.P. / A.S.P.P. MODULO B COMUNE';
update corso_alias set testo_origine = 'R.S.P.P. / A.S.P.P. modulo B', riga_foglio = 261 where testo = 'R.S.P.P. / A.S.P.P. MODULO B';
update corso_alias set testo_origine = 'R.S.P.P. / A.S.P.P. modulo B-SP1: Agricoltura - Pesca', riga_foglio = 262 where testo = 'R.S.P.P. / A.S.P.P. MODULO B-SP1: AGRICOLTURA - PESCA';
update corso_alias set testo_origine = 'R.S.P.P. / A.S.P.P. modulo B-SP2: Attività Estrattive- Costruzioni', riga_foglio = 263 where testo = 'R.S.P.P. / A.S.P.P. MODULO B-SP2: ATTIVITÀ ESTRATTIVE- COSTRUZIONI';
update corso_alias set testo_origine = 'R.S.P.P. / A.S.P.P. modulo B-SP3: Sanità residenziale', riga_foglio = 264 where testo = 'R.S.P.P. / A.S.P.P. MODULO B-SP3: SANITÀ RESIDENZIALE';
update corso_alias set testo_origine = 'R.S.P.P. / A.S.P.P. modulo B-SP4: Chimico - Petrolchimico', riga_foglio = 265 where testo = 'R.S.P.P. / A.S.P.P. MODULO B-SP4: CHIMICO - PETROLCHIMICO';
update corso_alias set testo_origine = 'R.S.P.P. DATORE DI LAVORO RISCHIO ALTO ', riga_foglio = 266 where testo = 'R.S.P.P. DATORE DI LAVORO RISCHIO ALTO';
update corso_alias set testo_origine = 'R.S.P.P. DATORE DI LAVORO RISCHIO BASSO', riga_foglio = 267 where testo = 'R.S.P.P. DATORE DI LAVORO RISCHIO BASSO';
update corso_alias set testo_origine = 'R.S.P.P. DATORE DI LAVORO RISCHIO MEDIO ', riga_foglio = 268 where testo = 'R.S.P.P. DATORE DI LAVORO RISCHIO MEDIO';
update corso_alias set testo_origine = 'Rischio chimico e biologico, sanificazione degli ambienti di lavoro, corretto uso dei DPI e procedure anticontagio Coronavirus.', riga_foglio = 269 where testo = 'RISCHIO CHIMICO E BIOLOGICO, SANIFICAZIONE DEGLI AMBIENTI DI LAVORO, CORRETTO USO DEI DPI E PROCEDURE ANTICONTAGIO CORONAVIRUS.';
update corso_alias set testo_origine = 'SVOLGIMENTO DI ATTIVITA'' IN QUOTA PER LAVORATORI ADDETTI ALL''INSTALLAZIONE E MANUTENZIONE DI PANNELLI FV', riga_foglio = 270 where testo = 'SVOLGIMENTO DI ATTIVITA'' IN QUOTA PER LAVORATORI ADDETTI ALL''INSTALLAZIONE E MANUTENZIONE DI PANNELLI FV';

-- ---------- i conti, e il terzo e quello che vale ----------
do $$
declare n_tot int; n_orig int; n_riga int; impronta text;
begin
  select count(*), count(testo_origine), count(riga_foglio)
    into n_tot, n_orig, n_riga from corso_alias;
  if n_tot <> 268 or n_orig <> 268 or n_riga <> 268 then
    raise exception 'attesi 268/268/268, trovati %/%/%', n_tot, n_orig, n_riga;
  end if;
  select encode(sha256(convert_to(string_agg(testo_origine, chr(10) order by riga_foglio), 'UTF8')), 'hex')
    into impronta from corso_alias;
  if impronta <> '9742ecef39efb97daf27279a6cfb17e0991884729eec053570f224ff50865f30' then
    raise exception 'impronta diversa: %', impronta;
  end if;
end $$;

commit;

-- **L'impronta va ricontrollata ordinando per `riga_foglio` e mai per `testo`.**
-- Un'impronta che non torna per una ragione procedurale segnala un problema che
-- non c'e, e la prossima volta nessuno ci crede piu.

